name: Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
        shell: bash

      - name: Get diff
        run: |
          git diff origin/${{ github.base_ref }}...HEAD > diff.txt
        shell: bash

      - name: Display diff
        run: |
          cat diff.txt

      - name: Run Code Review
        run: |
          curl -X POST https://696c-221-167-206-130.ngrok-free.app/ \
          -H "Content-Type: application/json" \
          -d "$(jq -n --arg diff "$(cat diff.txt)" --arg owner "${{ github.repository_owner }}" --arg repo "${{ github.event.repository.name }}" --arg pull_number "${{ github.event.number }}" '{diff: $diff, owner: $owner, repo: $repo, pull_number: $pull_number}')"
