name: Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract PR diff
        id: diff
        run: |
          git fetch origin main
          echo "::set-output name=diff::$(git diff origin/main HEAD)"

      - name: Review code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST https://696c-221-167-206-130.ngrok-free.app/ \
          -H "Content-Type: application/json" \
          -d "{\"diff\": \"${{ steps.diff.outputs.diff }}\", \"owner\": \"${{ github.repository_owner }}\", \"repo\": \"${{ github.event.repository.name }}\", \"pull_number\": ${{ github.event.number }}}"
